"""initial migration

Revision ID: 147427c09c1d
Revises: fdfeb0cc4271
Create Date: 2024-03-16 12:41:21.533578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147427c09c1d'
down_revision = 'fdfeb0cc4271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
