"""build migration

Revision ID: 934accbfe85a
Revises: 8485c33e315e
Create Date: 2024-03-16 12:54:16.786356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934accbfe85a'
down_revision = '8485c33e315e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
